### ISSUE TITLE
tomcat中启动报错

### ISSUE THREAD

**Issue by wuwen5** [alibaba/multi-thread-context#52]
```bash
-Xbootclasspath/a:/home/tomcat/tomcat/lib/multithread.context-1.2.0.jar
-javaagent:/home/tomcat/tomcat/lib/multithread.context-1.2.0.jar
```

是否是我使用的不对呢？
```
15:01:44.995 ERROR localhost-startStop-1-o.a.c.s.ContextConfig: Unable to process Jar entry [com/alibaba/mtc/javassist/ByteArrayClassPath.class] from Jar [jar:file:/home/tomcat/apache-tomcat-7.0.55/lib/multithread.context-1.2.0.jar!/] for annotations
java.io.EOFException: null
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340) ~[na:1.7.0_71]
	at org.apache.tomcat.util.bcel.classfile.Utility.swallowMethodParameters(Utility.java:797) ~[tomcat-coyote.jar:7.0.55]
	at org.apache.tomcat.util.bcel.classfile.Attribute.readAttribute(Attribute.java:171) ~[tomcat-coyote.jar:7.0.55]
	at org.apache.tomcat.util.bcel.classfile.FieldOrMethod.<init>(FieldOrMethod.java:57) ~[tomcat-coyote.jar:7.0.55]
	at org.apache.tomcat.util.bcel.classfile.Method.<init>(Method.java:71) ~[tomcat-coyote.jar:7.0.55]
	at org.apache.tomcat.util.bcel.classfile.ClassParser.readMethods(ClassParser.java:267) ~[tomcat-coyote.jar:7.0.55]
	at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:127) ~[tomcat-coyote.jar:7.0.55]
	at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2058) [catalina.jar:7.0.55]
	at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1934) [catalina.jar:7.0.55]
	at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1900) [catalina.jar:7.0.55]
	at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1885) [catalina.jar:7.0.55]
	at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1317) [catalina.jar:7.0.55]
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:876) [catalina.jar:7.0.55]
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:374) [catalina.jar:7.0.55]
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117) [catalina.jar:7.0.55]
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90) [catalina.jar:7.0.55]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5378) [catalina.jar:7.0.55]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.55]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1575) [catalina.jar:7.0.55]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1565) [catalina.jar:7.0.55]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_71]
	at com.alibaba.mtc.MtContextRunnable.run(MtContextRunnable.java:46) [na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
```

**Comment by oldratlee** [comment]
应该是`tomcat`的Bug：
http://stackoverflow.com/questions/25279729/tomcat-7-annotation-scanner-and-jdk-8-with-parameters-compiler-flag-exceptions

>Confirmed to be fixed in Tomcat 7.0.56
>
>See changelog for Tomcat 7.0.56 http://tomcat.apache.org/tomcat-7.0-doc/changelog.html
>
>Also tested this locally and it fixed my problems

你试试

**Comment by wuwen5** [comment]
非常感谢！这个问题ok了 现在有其他错误了，我先看看.

**Comment by wuwen5** [comment]
看了下，是javassist-3.19.0-GA版本中https://github.com/jboss-javassist/javassist/commit/c499faf6a8579cdfd266a22c2d5ef491d3bea6cb 
增加了编译器参数-parameters
```xml
<compilerArgument>-parameters</compilerArgument>
```
这个是java8才有的新特性，虽然target是1.6，但是增加了编译参数，编译出来的class字节码增加了元数据,导致tomcat bug暴露出来，tomcat 7.0.56修复了对MethodParameters的支持，但tomcat7最新版本中彻底去掉了swallowMethodParameters的处理。

感觉javassist-3.19.0 用了1.8的特性编译出来的major version: 50版本 不知道在jdk7以下版本会不会有其他兼容性问题。

**Comment by oldratlee** [comment]
> tomcat 7.0.56修复了对MethodParameters的支持，但tomcat7最新版本中彻底去掉了swallowMethodParameters的处理

由java8新功能引起来问题，Tomcat又对症下药了，应该问题不大。

**Comment by wuwen5** [comment]
@oldratlee javassist 已经fix了这个问题:blush:
https://github.com/jboss-javassist/javassist/commit/0e40ca2a33a9f01dd9ca813ef4b5dea60267fd09

之前给javassist提了个pr，已经合入主干了，javassist-3.19.0-GA版本 担心有兼容性问题，比如上次引发的tomcat bug。

**Comment by oldratlee** [comment]
牛B！！  :cow2:  :+1:

**Comment by wuwen5** [comment]
还没release， 从readme上看 应该计划在3.21版本中发布。
对应JASSIST-245

```
<h2>Changes</h2>

<p>-version 3.21
<ul>
<li>JIRA JASSIST-244, 245, 248, 255
</ul>
</p>

<p>-version 3.20 on June 25, 2015
<ul>
<li>JIRA JASSIST-241, 242, 246.
</ul>
</p>
```
